### ISSUE TITLE
Ideas, ideas ideas,

### ISSUE THREAD

**Issue by RadicaIization** [hecksalmonids/cobalt-cluster#38]
Mirror: Communications with other Disney partnered servers - Amphibia etc. like Yggdrasil. (Maybe too ambitious)
QOTD and MOTD.
Maybe announcements from the subreddit if that is not added correct me if I am wrong
Hekapoo's Dimensional Scissors where one can talk with people from the realm of Svtfoe (Too ambitious?)
A radio which links people's Disney Plus account or whatever account they watch svtfoe on to show other people what episode they are on (kinda useless cause the show ended :( )

**Comment by CorruptedPhazite** [comment]
Please resubmit. Each suggestion must be submitted individually.
